name: Recent blog post update
on:
  # schedule:
  #   - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with recent blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://guisso.dev/en/posts/index.xml"
